### PR TITLE
Split json to smaller files

### LINKED ISSUE #186: Split links JSON into multiple JSON
The links JSON is already 800 lines long.
As we accrue more and more categories and link, it will become unruly.
I suggest we split to folders per category, and in each folder split to sub-categories. 

Something like:
* `/_data/links.json` (if we ever want top-level (no category) links
*  `/_data/mentalHealth/links.json` (if we ever want top-level (no category) links
* `/_data/mentalHealth/psychology/links.json` (if we ever want top-level (no category) links

We can always combine them to one large JSON in the CI (if it makes Jekyll templating easier / requires less changes).

### PR DESCRIPTION
**Pull request by chiptus**
close #186

### CODE REVIEW

**Comment by chiptus** [comment]
the only problem IMO is the file order. currently I just gave each file an index.

maybe something like this will work (my ruby is rusty) https://stackoverflow.com/a/33215732/681629

**Review by 4tal — CHANGES_REQUESTED** [review]
We should solve the order issue first

**Comment by 4tal** [comment]
Master Liquid Ruby

**Review by 4tal — APPROVED** [review]

**Comment by ohadschn** [comment]
> @ohadschn I don't think jekyll has built-in support for sub folders.
> 
> Also, I can't solve the issue with the order.
> 
> IMO it will be better to merge it like this, then make improvements later, because we will have merge conflicts with any added site

Liquid sucks, but I got it to work: https://github.com/4tals/LinksForIsrael/pull/226

**Pull request merged**
